-- INSERTING AUTHORS STEP 2
INSERT INTO authors (author_id, author_name, bio, image_url)
VALUES
(
    31,
    'Alex Michaelides',
    'Cypriot-British author best known for psychological thriller novels, especially The Silent Patient.',
    'https://rokbucket.rokomari.io/people/cf63cdfb6_75772.jpg'
),
(
    32,
    'Haruki Murakami',
    'Japanese novelist known for blending surrealism, loneliness, memory, and popular culture in works such as Norwegian Wood and Kafka on the Shore.',
    'https://rokbucket.rokomari.io/people/807656878324_22595.jpg'
),
(
    33,
    'Fyodor Dostoevsky',
    'Russian novelist known for exploring psychology, morality, faith, and human nature in works such as Crime and Punishment.',
    'https://rokbucket.rokomari.io/people/ee0edd99d_8600.jpg'
),
(
    34,
    'Jane Austen',
    'English novelist known for her sharp social commentary and classic novels including Pride and Prejudice.',
    'https://rokbucket.rokomari.io/people/cf420facd3f4_11575.jpg'
),
(
    35,
    'Khaled Hosseini',
    'Afghan-American novelist known for emotionally powerful stories about family, friendship, and life in Afghanistan.',
    'https://rokbucket.rokomari.io/people/a4316372e_15474.jpg'
),
(
    36,
    'Markus Zusak',
    'Australian author best known for The Book Thief, a novel set during World War II.',
    'https://rokbucket.rokomari.io/people/043b255cade4_30906.jpg'
),
(
    37,
    'Yann Martel',
    'Canadian author best known for Life of Pi, a novel combining adventure, philosophy, spirituality, and storytelling.',
    NULL
),
(
    38,
    'F. Scott Fitzgerald',
    'American novelist and short-story writer associated with the Jazz Age and best known for The Great Gatsby.',
    NULL
),
(
    39,
    'George Orwell',
    'English novelist and essayist best known for 1984 and Animal Farm.',
    'https://rokbucket.rokomari.io/people/03df86f8b_3183.jpg'
),
(
    40,
    'Ernest Hemingway',
    'American novelist and short-story writer known for his concise writing style and works such as The Old Man and the Sea.',
    'https://rokbucket.rokomari.io/people/6ed00def1_2344.jpg'
),
(
    41,
    'Franz Kafka',
    'German-speaking Bohemian writer known for influential works exploring alienation, anxiety, and absurdity.',
    'https://rokbucket.rokomari.io/people/21b6bd70d724_20368.jpg'
),
(
    42,
    'James Clear',
    'American author known for writing about habits, decision-making, and continuous improvement, especially in Atomic Habits.',
    'https://rokbucket.rokomari.io/people/614a52d76_78113.jpg'
),
(
    43,
    'শরৎচন্দ্র চট্টোপাধ্যায়',
    'বাংলা সাহিত্যের অন্যতম জনপ্রিয় ঔপন্যাসিক, যিনি মানবজীবন, সমাজ ও সম্পর্কের বাস্তবধর্মী চিত্র তুলে ধরেছেন।',
    'https://rokbucket.rokomari.io/people/406a18f04ae4_6684.jpg'
),
(
    44,
    'Robert C. Martin',
    'American software engineer and author widely known for Clean Code and his contributions to software craftsmanship.',
    ''
),
(
    45,
    'Thomas H. Cormen',
    'American computer scientist and co-author of Introduction to Algorithms.',
    NULL
),
(
    46,
    'Charles E. Leiserson',
    'American computer scientist known for his work in algorithms and parallel computing and co-author of Introduction to Algorithms.',
    NULL
),
(
    47,
    'Ronald L. Rivest',
    'American computer scientist known for his contributions to cryptography and algorithms and co-author of Introduction to Algorithms.',
    NULL
),
(
    48,
    'Clifford Stein',
    'American computer scientist and co-author of Introduction to Algorithms, with research interests in algorithms and optimization.',
    NULL
),
(
    49,
    'Morgan Housel',
    'American author and investor known for his writing about personal finance, investing, wealth, and human behavior.',
    'https://rokbucket.rokomari.io/people/99d02ae9c_88204.jpg'
),
(

    50,
    'সৈয়দ ওয়ালীউল্লাহ',
    'বাংলা সাহিত্যের অন্যতম গুরুত্বপূর্ণ কথাসাহিত্যিক। তাঁর লেখায় গ্রামীণ সমাজ, ধর্মীয় কুসংস্কার, সামাজিক বাস্তবতা, মানুষের বিশ্বাস এবং মানবমনের জটিলতা গভীরভাবে ফুটে উঠেছে।',
    'https://rokbucket.rokomari.io/people/f6f67402b2d4_3306.jpg'

);