INSERT INTO BOOKS
(BOOK_ID, TITLE, PRICE, STOCK, TOTAL_SOLD, DESCRIPTION, ADMIN_ID, PUBLISHER_ID, IMAGE_URL)
VALUES
(211, 'পথের পাঁচালী', 350, 20, 0,
'বিভূতিভূষণ বন্দ্যোপাধ্যায়ের বিখ্যাত উপন্যাস। অপু ও দুর্গার শৈশব এবং গ্রামীণ বাংলার জীবনকে কেন্দ্র করে রচিত।',
104, 1, 'image/book_cover/pother_pachali2.jpeg'),

(212, 'দেবদাস', 300, 25, 0,
'শরৎচন্দ্র চট্টোপাধ্যায়ের বিখ্যাত প্রেমের উপন্যাস। দেবদাস, পার্বতী ও চন্দ্রমুখীর জীবনকে ঘিরে গল্পটি আবর্তিত।',
107, 1, 'image/book_cover/devdas2.jpeg'),

(213, 'Strikanta', 450, 18, 0,
'A timeless Bengali novel by Sarat Chandra Chattopadhyay, Srikanta follows the life and journeys of its wandering protagonist as he travels through different places and encounters people from various walks of life. Through his experiences, friendships, love, and emotional struggles, the novel explores the complexities of human relationships, society, freedom, and the search for meaning in life. Rich in emotion and vivid observations of Bengali society, Srikanta remains one of Sarat Chandra Chattopadhyay’s most celebrated works.',
105, 1, 'image/book_cover/srikanta_english.jpeg'),

(214, 'সেই সময়', 550, 15, 0,
'সুনীল গঙ্গোপাধ্যায়ের ঐতিহাসিক উপন্যাস। উনিশ শতকের বাংলার সমাজ, সংস্কৃতি ও পরিবর্তনের চিত্র এতে ফুটে উঠেছে।',
104, 1, 'image/book_cover/sheishomoy.jpeg'),

(215, 'হাজার বছর ধরে', 400, 22, 0,
'জহির রায়হানের বিখ্যাত উপন্যাস। বাংলার গ্রামীণ মানুষের জীবন, দারিদ্র্য, ভালোবাসা ও সংগ্রামের গল্প।',
104, 1, 'image/book_cover/hajar_bochor_dhore.jpeg'),

(216, 'লালসালু', 380, 20, 0,
'সৈয়দ ওয়ালীউল্লাহর বিখ্যাত উপন্যাস। ধর্মীয় কুসংস্কার, ক্ষমতা ও গ্রামীণ সমাজের বাস্তবতাকে কেন্দ্র করে রচিত।',
105, 1, 'image/book_cover/hajar_bochor_dhore.jpeg'),

(217, 'হিমু', 320, 30, 0,
'হুমায়ূন আহমেদের জনপ্রিয় চরিত্র হিমুকে কেন্দ্র করে লেখা উপন্যাস। হিমুর অদ্ভুত জীবনদর্শন ও বিচিত্র অভিজ্ঞতার গল্প।',
105, 1, 'image/book_cover/himu.jpeg'),

(218, 'মিসির আলি সমগ্র', 700, 12, 0,
'হুমায়ূন আহমেদের রহস্যময় চরিত্র মিসির আলিকে কেন্দ্র করে বিভিন্ন মনস্তাত্ত্বিক রহস্য ও ঘটনার সংকলন।',
108, 1, 'image/book_cover/misir_ali_shomogro.jpeg'),

(219, 'কৃষ্ণপক্ষ', 350, 24, 0,
'হুমায়ূন আহমেদের আবেগঘন উপন্যাস। ভালোবাসা, সম্পর্ক ও জীবনের অনিশ্চয়তাকে কেন্দ্র করে গল্পটি গড়ে উঠেছে।',
104, 1, 'image/book_cover/krishnopokkho.jpeg'),

(220, 'চাঁদের পাহাড়', 380, 20, 0,
'বিভূতিভূষণ বন্দ্যোপাধ্যায়ের রোমাঞ্চকর উপন্যাস। আফ্রিকার অজানা জগতে শঙ্করের অভিযান ও দুঃসাহসিক অভিজ্ঞতার গল্প।',
106, 1, 'image/book_cover/chander_pahar2.jpeg');