INSERT INTO book_authors (book_id, author_id)
VALUES
-- Foreign / English books

(1001, 32), -- Norwegian Wood → Haruki Murakami
(1002, 32), -- Kafka on the Shore → Haruki Murakami
(1003, 33), -- Crime and Punishment → Fyodor Dostoevsky
(1004, 34), -- Pride and Prejudice → Jane Austen
(1005, 35), -- The Kite Runner → Khaled Hosseini
(1006, 35), -- A Thousand Splendid Suns → Khaled Hosseini
(1007, 36), -- The Book Thief → Markus Zusak
(1008, 37), -- Life of Pi → Yann Martel
(1009, 38), -- The Great Gatsby → F. Scott Fitzgerald
(1010, 39), -- Animal Farm → George Orwell
(1011, 29), -- The Alchemist → Paulo Coelho
(1012, 29), -- The Alchemist → Paulo Coelho
(1013, 31), -- The Silent Patient → Alex Michaelides
(1014, 26), -- Harry Potter → J.K. Rowling
(1015, 39), -- 1984 → George Orwell
(1016, 40), -- The Old Man and the Sea → Ernest Hemingway
(1017, 16), -- Inferno → Dan Brown
(1018, 16), -- Angels and Demons → Dan Brown
(1019, 16), -- The Da Vinci Code → Dan Brown
(1020, 16), -- Origin → Dan Brown
(1021, 25), -- The Shining → Stephen King
(1022, 41), -- Metamorphosis → Franz Kafka

-- Humayun Ahmed
(1023, 1), -- হিমু
(1024, 1), -- দেবী
(1025, 1), -- নন্দিত নরকে
(1026, 1), -- কোথাও কেউ নেই
(1027, 1), -- শঙ্খনীল কারাগার
(1028, 1), -- শ্রাবণ মেঘের দিন

-- Bengali books
(1029, 9), -- পথের পাঁচালী → বিভূতিভূষণ বন্দ্যোপাধ্যায়
(1030, 9), -- অপরাজিত → বিভূতিভূষণ বন্দ্যোপাধ্যায়
(1031, 9), -- চাঁদের পাহাড় → বিভূতিভূষণ বন্দ্যোপাধ্যায়
(1032, 20), -- পদ্মা নদীর মাঝি → মানিক বন্দ্যোপাধ্যায়

-- Rabindranath Tagore
(1035, 3), -- শেষের কবিতা
(1036, 3), -- চোখের বালি

-- Other
(1037, 42), -- Atomic Habits → James Clear

(1033, 43), -- দেবদাস → শরৎচন্দ্র চট্টোপাধ্যায়
(1034, 43), -- শ্রীকান্ত → শরৎচন্দ্র চট্টোপাধ্যায়

(1038, 44), -- Clean Code → Robert C. Martin

(1039, 45), -- Introduction to Algorithms → Thomas H. Cormen
(1039, 46), -- Introduction to Algorithms → Charles E. Leiserson
(1039, 47), -- Introduction to Algorithms → Ronald L. Rivest
(1039, 48), -- Introduction to Algorithms → Clifford Stein

(1040, 49); -- The Psychology of Money → Morgan Housel