INSERT INTO BOOK_CATEGORIES (BOOK_ID, CATEGORY_ID)
VALUES
(211, 1),   -- পথের পাঁচালী → Novel
(212, 7),   -- দেবদাস → Romance
(213, 1),   -- শ্রীকান্ত → Novel
(214, 9),   -- সেই সময় → Historical
(215, 1),   -- হাজার বছর ধরে → Novel
(216, 1),   -- লালসালু → Novel
(217, 1),   -- হিমু → Novel
(218, 3),   -- মিসির আলি সমগ্র → Mystery
(219, 7),   -- কৃষ্ণপক্ষ → Romance
(220, 8);   -- চাঁদের পাহাড় → Adventure